stages:
  - build
#  - test
#  - review
  - deploy

build-job:
  tags:
    - test
  stage: build
  image: node:16-alpine
  script:
    - cd front
    - npm ci --legacy-peer-deps
    - npm run build
    - echo "Project was successfully built."

deploy-job:
  only:
    - main
  tags:
    - review
  stage: deploy
  variables:
    FRONT_PORT: 3085
    CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA
    CI_COMMIT_TIMESTAMP: $CI_COMMIT_TIMESTAMP
    CI_COMMIT_TITLE: $CI_COMMIT_TITLE
  script:
    - docker image prune -f
    - docker compose down
    - docker compose build --no-cache
    - docker compose up -d
