version: '3.1'
services:
  front:
    build:
      context: front/
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./front:/front
      - /front/node_modules
      - /front/.next
