[[redirects]]
  from = "/studio"
  to = "/studio"
  status = 200

[[redirects]]
  from = "/production"
  to = "/production"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200